package it.emanuelemelini.photocal.data.crea

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/** Food from the CREA tables, values per 100 g of edible portion. */
data class CreaFood(
    val code: String,
    val name: String,
    val category: String,
    val kcal: Double,
    val proteinG: Double?,
    val fatG: Double?,
    val carbsG: Double?,
)

/**
 * CREA food composition tables (assets/crea_foods.tsv, generated by
 * tools/crea/build_crea_table.py). A few hundred rows: kept in memory.
 */
class CreaTable(private val context: Context) {

    private val foods: Map<String, CreaFood> by lazy { load() }

    suspend fun get(code: String): CreaFood? = withContext(Dispatchers.IO) { foods[code.trim()] }

    /** "code|name" list passed to the AI so it can pick the matching food. */
    suspend fun catalog(): String = withContext(Dispatchers.IO) {
        foods.values.joinToString("\n") { "${it.code}|${it.name}" }
    }

    private fun load(): Map<String, CreaFood> =
        context.assets.open(ASSET).bufferedReader().useLines { lines ->
            lines
                .filterNot { it.startsWith("#") || it.isBlank() }
                .drop(1) // header
                .mapNotNull(::parse)
                .associateBy { it.code }
        }

    private fun parse(line: String): CreaFood? {
        val cols = line.split('\t')
        if (cols.size < COLUMN_COUNT) return null
        return CreaFood(
            code = cols[0],
            name = cols[1],
            category = cols[2],
            kcal = cols[5].toDoubleOrNull() ?: return null,
            proteinG = cols[6].toDoubleOrNull(),
            fatG = cols[7].toDoubleOrNull(),
            carbsG = cols[8].toDoubleOrNull(),
        )
    }

    companion object {
        const val SOURCE = "CREA – Tabelle di composizione degli alimenti (alimentinutrizione.it)"
        private const val ASSET = "crea_foods.tsv"
        private const val COLUMN_COUNT = 10
    }
}
